# print("="*10," INPUT DATA DIRI ","="*10)

# print("-"*30)
# nama = input("Siapa Nama Anda = ")
# nim = input("Berapa NIM Anda = ")
# jurusan = input("Apa Jurusan Anda = ")
# alamat = input("Dimana Alamat Anda = ")

# print()
# print("="*10," KARTU TANDA MAHASISWA ","="*10)
# print(f"Nama : {nama}")
# print(f"NIM : {nim}")
# print(f"Prodi : {jurusan}")
# print(f"Alamat : {alamat}")

kalimat = input()

print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
print(kalimat)
